title: Andre Firmansah
markdown: kramdown
url: ""
baseurl: "/"

# for atom feed
author:
  name: Andre Kusuma Firmansah
  email: andrekusuma388@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-google-search-console-verification-file

paginate: 4
paginate_path: "/page:num/"

ganalytics: G-2XZRLPNSDB
google_search_console:
  verification_file_code: 54b942591f95001
google_site_verification: 3oKKw2iZEUNRxHCa9ii5MZf8I3Oz7sVsWOT8MupIdOE

enable_google_verification: true

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
